### ISSUE TITLE
Bug: Philares should get greeneries conversion if they gain plant from players that go before them during the end game conversion

### ISSUE THREAD

**Issue by vsrisuknimit** [terraforming-mars/terraforming-mars#2978]
![image](https://user-images.githubusercontent.com/14239220/111612614-03a5e980-87b4-11eb-90b8-9f17a079c90c.png)

![image](https://user-images.githubusercontent.com/14239220/111612670-128c9c00-87b4-11eb-8363-907785e7a581.png)

1. Gingerly (RED) had 7 plants. So the app does not offer her a choice for greenery conversion.
2. RED gained one more plant due to Philares power after markanarmi (ORANGE) placed a greenery at (7,2). 
3. Because markanarmi (ORANGE) went before Gingerly (RED) during the final greenery conversion round, Gingerly (RED) should be able to place her last greenery. 

Currently the game does not offer Philares a chance to convert if Philares does not have 8 plants to begin with even though it might gain plant during other player's conversion.

#2315 fixed a different problem but caused this one. 

Tagging @nwai90 .

**Comment by ltdstudio** [comment]
I have this problem too.
so I paste my situatuion to here.

I found a bug when game end and player place the last green block.

If Philares Corp player place last block at frist. after this step player have 7 green RES
then other play place block near Philares Corp player bloak , Philares Corp player green RES rise to 8.
Server will crash.

Server terminal log:

2021-03-18 11:07:45 GMT+0800] Error processing input from player Error: Too many cards selected
at Player.runInput (/home/ddd/terraforming-mars/build/src/Player.js:732:23)
at Player.runInput (/home/ddd/terraforming-mars/build/src/Player.js:717:18)
at Player.process (/home/ddd/terraforming-mars/build/src/Player.js:1642:18)
at IncomingMessage. (/home/ddd/terraforming-mars/build/src/routes/PlayerInput.js:55:24)
at Object.onceWrapper (events.js:286:20)
at IncomingMessage.emit (events.js:203:15)
at endReadableNT (_stream_readable.js:1145:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
[2021-03-18 11:16:00 GMT+0800] Error processing input from player Error: Card not found
at Player.getCard (/home/ddd/terraforming-mars/build/src/Player.js:640:19)
at _loop_1 (/home/ddd/terraforming-mars/build/src/Player.js:736:41)
at Player.runInput (/home/ddd/terraforming-mars/build/src/Player.js:744:17)
at Player.runInput (/home/ddd/terraforming-mars/build/src/Player.js:717:18)
at Player.process (/home/ddd/terraforming-mars/build/src/Player.js:1642:18)
at IncomingMessage. (/home/ddd/terraforming-mars/build/src/routes/PlayerInput.js:55:24)
at Object.onceWrapper (events.js:286:20)
at IncomingMessage.emit (events.js:203:15)
at endReadableNT (_stream_readable.js:1145:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
[2021-03-18 13:47:23 GMT+0800] Not found GET /api/player?id=p27910a97d8f4
[2021-03-19 20:34:36 GMT+0800] Error processing input from player Error: Number not provided for amount
at Player.runInput (/home/ddd/terraforming-mars/build/src/Player.js:690:23)
at Player.runInput (/home/ddd/terraforming-mars/build/src/Player.js:682:22)
at Player.process (/home/ddd/terraforming-mars/build/src/Player.js:1642:18)
at IncomingMessage. (/home/ddd/terraforming-mars/build/src/routes/PlayerInput.js:55:24)
at Object.onceWrapper (events.js:286:20)
at IncomingMessage.emit (events.js:203:15)
at endReadableNT (_stream_readable.js:1145:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
[2021-03-19 21:09:29 GMT+0800] Not found GET /nice%20ports%2C/Tri%6Eity.txt%2ebak
[2021-03-19 21:34:11 GMT+0800] Error processing input from player Error: Not enough cards selected
at Player.runInput (/home/ddd/terraforming-mars/build/src/Player.js:729:23)
at Player.runInput (/home/ddd/terraforming-mars/build/src/Player.js:717:18)
at Player.process (/home/ddd/terraforming-mars/build/src/Player.js:1642:18)
at IncomingMessage. (/home/ddd/terraforming-mars/build/src/routes/PlayerInput.js:55:24)
at Object.onceWrapper (events.js:286:20)
at IncomingMessage.emit (events.js:203:15)
at endReadableNT (_stream_readable.js:1145:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
[2021-03-19 22:08:14 GMT+0800] Not found GET /main.js?visitDstTime=1
[2021-03-19 22:08:27 GMT+0800] Not found GET /main.js?visitDstTime=1
[2021-03-19 22:15:59 GMT+0800] Not found GET /main.js?visitDstTime=1
[2021-03-19 22:16:29 GMT+0800] Not found GET /main.js?visitDstTime=1
[2021-03-19 22:21:15 GMT+0800] Not found GET /main.js?visitDstTime=1
[2021-03-19 22:33:34 GMT+0800] SQLite:saveGameResults { [Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: game_results.game_id] errno: 19, code: 'SQLITE_CONSTRAINT' }
undefined:0

Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: game_results.game_id
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! terraforming-mars@1.0.0 start: node build/src/server.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the terraforming-mars@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /home/ddd/.npm/_logs/2021-03-19T14_33_34_886Z-debug.log

2021-03-19T14_33_34_886Z-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle terraforming-mars@1.0.0prestart: terraforming-mars@1.0.0
6 info lifecycle terraforming-mars@1.0.0start: terraforming-mars@1.0.0
7 verbose lifecycle terraforming-mars@1.0.0start: unsafe-perm in lifecycle true
8 verbose lifecycle terraforming-mars@1.0.0start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ddd/terraforming-mars/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle terraforming-mars@1.0.0start: CWD: /home/ddd/terraforming-mars
10 silly lifecycle terraforming-mars@1.0.0start: Args: [ '-c', 'node build/src/server.js' ]
11 silly lifecycle terraforming-mars@1.0.0start: Returned: code: 1 signal: null
12 info lifecycle terraforming-mars@1.0.0start: Failed to exec start script
13 verbose stack Error: terraforming-mars@1.0.0 start: node build/src/server.js
13 verbose stack Exit status 1
13 verbose stack at EventEmitter. (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack at EventEmitter.emit (events.js:198:13)
13 verbose stack at ChildProcess. (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack at ChildProcess.emit (events.js:198:13)
13 verbose stack at maybeClose (internal/child_process.js:982:16)
13 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid terraforming-mars@1.0.0
15 verbose cwd /home/ddd/terraforming-mars
16 verbose Linux 5.8.0-43-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
18 verbose node v10.19.0
19 verbose npm v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error terraforming-mars@1.0.0 start: node build/src/server.js
22 error Exit status 1
23 error Failed at the terraforming-mars@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by kberg** [comment]
I have manually verified this works.
