### ISSUE TITLE
Cannot create a game with custom colonies

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#4161]
To reproduce:
* Go to /new-game
* Click Colonies
* Click Custom Colonies
* Click one of the colonies
* Click the create button

Game isn't created. Server error is 

```
[2022-02-26 18:38:35 EST] internal server error:  /game TypeError: Cannot read properties of undefined (reading 'colonies')
    at .../git/terraforming-mars/build/src/colonies/Colony.js:265:30
    at Array.map (<anonymous>)
    at serializeColonies (.../git/terraforming-mars/build/src/colonies/Colony.js:263:21)
    at Game.serialize (.../git/terraforming-mars/build/src/Game.js:298:54)
    at Localfilesystem.saveGame (.../git/terraforming-mars/build/src/database/LocalFilesystem.js:70:38)
    at Game.save (.../git/terraforming-mars/build/src/Game.js:287:43)
    at Game.gotoInitialResearchPhase (.../git/terraforming-mars/build/src/Game.js:552:14)
    at Function.Game.newInstance (.../git/terraforming-mars/build/src/Game.js:282:18)
    at IncomingMessage.<anonymous> (.../git/terraforming-mars/build/src/routes/Game.js:128:44)
```

which is roughly here

```
export function serializeColonies(colonies: Array<Colony>): Array<SerializedColony> {
  return colonies.map((colony) => {
    return {
      colonies: colony.colonies,
      name: colony.name,
      isActive: colony.isActive,
      resourceType: colony.resourceType,
      trackPosition: colony.trackPosition,
      visitor: colony.visitor,
    };
  });
}
```

**Comment by kberg** [comment]
This has been fixed.
