### ISSUE TITLE
Unexpected server response: Not Found

### ISSUE THREAD

**Issue by DERTAZ** [terraforming-mars/terraforming-mars#4798]
hello, during the game 3 days ago, after about the 10th / 11th generation, we popped up with the "Unexpected server response: Not Found" message, I thought that after one of the server resets the game will repair, because it was like that many times (e.g. when it got stuck with an unplayable move) . But it's been a long time and I still get this message, link to the game: https://terraforming-mars.herokuapp.com/game?id=g98dee3633452

**Comment by kberg** [comment]
@DERTAZ how long ago did the game start? Games get deleted after ~10 days, even if they're not finished.. It's not exact, but it's around 10 days.

**Comment by DERTAZ** [comment]
table created on Friday, August 19 at 8:00 and around 10:00 has stopped working and the message is popping up: Unexpected server response: Not Found. 
Is there a chance to fix it, or someone knows why the game broke when we were more or less in the middle of the game (10/11 generation)

**Comment by kberg** [comment]
Found it. Yeah, wow, somehow this game is a little broken.

```
2022-08-25T05:33:03.317378+00:00 app[web.1]: [2022-08-25 05:33:03 GMT+0000] unable to find player pede232682026 RangeError: Maximum call stack size exceeded
2022-08-25T05:33:03.317380+00:00 app[web.1]:     at Player.canPlay (/app/build/src/server/Player.js:1014:12)
2022-08-25T05:33:03.317380+00:00 app[web.1]:     at /app/build/src/server/cards/pathfinders/Odyssey.js:36:24
2022-08-25T05:33:03.317380+00:00 app[web.1]:     at Array.filter (<anonymous>)
2022-08-25T05:33:03.317382+00:00 app[web.1]:     at Odyssey.availableEventCards (/app/build/src/server/cards/pathfinders/Odyssey.js:33:35)
2022-08-25T05:33:03.317382+00:00 app[web.1]:     at Odyssey.canAct (/app/build/src/server/cards/pathfinders/Odyssey.js:43:21)
2022-08-25T05:33:03.317383+00:00 app[web.1]:     at ProjectInspection.getActionCards (/app/build/src/server/cards/promo/ProjectInspection.js:30:70)
2022-08-25T05:33:03.317383+00:00 app[web.1]:     at ProjectInspection.canPlay (/app/build/src/server/cards/promo/ProjectInspection.js:37:21)
2022-08-25T05:33:03.317383+00:00 app[web.1]:     at Player.canPlayIgnoringCost (/app/build/src/server/Player.js:1021:21)
2022-08-25T05:33:03.317384+00:00 app[web.1]:     at Player.canPlay (/app/build/src/server/Player.js:1015:49)
2022-08-25T05:33:03.317384+00:00 app[web.1]:     at /app/build/src/server/cards/pathfinders/Odyssey.js:36:24
2022-08-25T05:33:03.317453+00:00 app[web.1]: [2022-08-25 05:33:03 GMT+0000] Not found GET /api/player?id=pede232682026

```

**Comment by kberg** [comment]
I will try to fix this in the next two  days, but I'm not so sure I can.

**Comment by kberg** [comment]
Actually, yeah, I see it. I am writing a fix now.

**Comment by DERTAZ** [comment]
hello, thanks for repairing our Mars Terraformation game, after your repair we were able to finish the game without any problems.   Big thank you.  
            
          
     
      
       
        Dnia 25 sierpnia 2022 07:46 Robert Konigsberg ***@***.***&gt; napisał(a):
       
    
       
         
 Actually, yeah, I see it. I am writing a fix now.
