### ISSUE TITLE
zod error - Expected number, received string

### ISSUE THREAD

**Issue by nobanzai** [terraforming-mars/terraforming-mars#6528]
Starting with yesterday's server version I get the error shown below after clicking "create game".
If I recover
deployed: Mon, 25 Mar 2024 09:27:38 -0400 - version: acd26543a
everything works fine.
System is openSUSE Tumbleweed 20240326 with nodejs20-20.11.1-1.1.x86_64 and nodejs-common-6.1-1.2.x86_64.

internal server error:  /game ZodError: [
  {
    "code": "invalid_type",
    "expected": "number",
    "received": "string",
    "path": [
      "startingCorporations"
    ],
    "message": "Expected number, received string"
  }
]
    at get error [as error] (Terraforming_Mars/node_modules/zod/lib/types.js:43:31)
    at ZodObject.parse (Terraforming_Mars/node_modules/zod/lib/types.js:143:22)
    at IncomingMessage.<anonymous> (Terraforming_Mars/build/src/server/routes/Game.js:85:67)
    at Object.onceWrapper (node:events:633:28)
    at IncomingMessage.emit (node:events:519:28)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  issues: [
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'string',
      path: [Array],
      message: 'Expected number, received string'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'string',
      path: [Array],
      message: 'Expected number, received string'
    }
  ]
}

**Comment by kberg** [comment]
I'm rolling back a change which should remove this error. Thank you!

**Comment by nobanzai** [comment]
State back to normal - thx!
Happy Easter!
