### ISSUE TITLE
Error: Undefined quota

### ISSUE THREAD

**Issue by nobanzai** [terraforming-mars/terraforming-mars#6532]
With Version: 44a2add15 I get the following error message, when starting the server on my openSUSE Tumbleweed box.
Nevertheless the server is starting and seems to work without any problems.

[2024-03-29 12:56:33 GMT+0100] Error: Undefined quota
    at get Terraforming_Mars/build/src/server/routes/Game.js:24:19)
    at new GameHandler Terraforming_Mars/build/src/server/routes/Game.js:50:31)
    at Object.<anonymous> (Terraforming_Mars/build/src/server/routes/Game.js:170:24)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (Terraforming_Mars/build/src/server/server/requestProcessor.js:17:16)

**Comment by kberg** [comment]
Still an issue?

**Comment by kberg** [comment]
Ah, I see that it would still be. I've restructured the code to spit out nicer warning messages.
