### ISSUE TITLE
Error processing input from player Error: Not enough cards selected

### ISSUE THREAD

**Issue by nobanzai** [terraforming-mars/terraforming-mars#6551]
Could you please do "restructure" the code for the following error message, too? TIA!

[2024-04-02 23:11:55 GMT+0200] Error processing input from player Error: Not enough cards selected
    at SelectCard.process (Terraforming_Mars/build/src/server/inputs/SelectCard.js:45:19)
    at Player.runInput (Terraforming_Mars/build/src/server/Player.js:394:27)
    at OrOptions.process (Terraforming_Mars/build/src/server/inputs/OrOptions.js:30:16)
    at Player.runInput (Terraforming_Mars/build/src/server/Player.js:394:27)
    at Player.process (Terraforming_Mars/build/src/server/Player.js:1356:18)
    at IncomingMessage.<anonymous> (Terraforming_Mars/build/src/server/routes/PlayerInput.js:85:32)
    at Object.onceWrapper (node:events:633:28)
    at IncomingMessage.emit (node:events:519:28)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by nobanzai** [comment]
Thx!
