### ISSUE TITLE
Adding cards from other expansions with custom board spaces breaks games

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#6948]
From Discord at https://discord.com/channels/737945098695999559/742721510376210583/1276758455222403073
> {
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=sf40cc55ac19d",
  "color": "blue",
  "step": 113,
  "version": "787f31d",
  "builtAt": "Tue, 13 Aug 2024 03:42:05 GMT",
  "browser": "Safari 17",
  "language": "en",
  "experimental_ui": false
}

Creating a colony on Luna is creating some form of infinite loop.

**Comment by kberg** [comment]
```
[2024-08-24 00:39:31 EDT] Not found GET /api/game?id=g8d9685d3cbc8
[2024-08-24 00:39:31 EDT] Loading g8d9685d3cbc8
[2024-08-24 00:39:31 EDT] saving g8d9685d3cbc8 at position 112
[2024-08-24 00:39:31 EDT] GameLoader:loadGame Error: Can't find space with id 76
    at TharsisBoard.getSpaceOrThrow (/home/kberg/git/terraforming-mars/build/src/server/boards/Board.js:31:19)
    at Executor.canExecute (/home/kberg/git/terraforming-mars/build/src/server/behavior/Executor.js:144:32)
    at DysonScreens.canPlay (/home/kberg/git/terraforming-mars/build/src/server/cards/Card.js:153:63)
```

**Comment by maserion** [comment]
https://github.com/terraforming-mars/terraforming-mars/blob/58244ee228a5a122dbf56708f32106d6fc1c337d/src/server/boards/BoardBuilder.ts#L86
Shouldn't these cases be lifted to deal with it? All space city places will be available in all games in this way, but some of them won't be usable at all due to lack of cards in deck (and that won't change anything I guess). The only edge case is probably Star Vegas.

**Comment by kberg** [comment]
That's one spot of many.

**Comment by kberg** [comment]
This looks well managed now.
